#!/usr/bin/env bash
set -e

usage()
{
    cat << USAGE >&2
Usage:
    monitor-wait name ...
USAGE
    exit 1
}

if [ $# -lt 1 ]; then
	usage
fi

dir=/monitor

for name in "$@"; do
	echo "Waiting for ${name}"
	FILE=${dir}/${name}
	while [ ! -f "$FILE" ]; do
		sleep 1
	done
	echo "Completed waiting for ${name}"
done;