#!/usr/bin/env bash
usage()
{
    cat << USAGE >&2
Usage:
    monitor-wait name
USAGE
    exit 1
}

if [ $# -ne 1 ]; then
	usage
fi

NAME=$1
FILE=/monitor/${NAME}
if [ -f "$FILE" ]; then
	echo "Already notified"
	exit 1
fi

echo "Waiting for $NAME"
while [ ! -f "$FILE" ]; do
	sleep 1
done
echo "Completed waiting for $NAME"