#!/usr/bin/env bash
set -e

usage()
{
    cat << USAGE >&2
Usage:
    monitor-notify name ...
USAGE
    exit 1
}

if [ $# -lt 1 ]; then
	usage
fi

dir=/monitor

for name in "$@"; do
	file=${dir}/${name}
	touch $file
	echo "Notified ${name}"
done;